---
stages:
  - build
  - test

.build:
  stage: build
  # TODO: Move to `variables` section when possible.
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1809
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
  script:
    - ./gradlew assemble
  cache:
    key: $CI_JOB_NAME
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build # Actually, caching build does not work because of files' access / modification time. Probably will be working one day.

# Run unit tests.
# Actually, unit tests parse https://www.packtpub.com/packt/offers/free-learning, so it is not "true" unit tests.
.unit:
  stage: test
  # TODO: Move to `variables` section when possible.
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/1809
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
  script:
    - ./gradlew test jacocoTestReport
    - bash <(curl -s https://codecov.io/bash)
  cache:
    key: $CI_JOB_NAME
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build # Actually, caching build does not work because of files' access / modification time. Probably will be working one day.
  artifacts:
    reports:
      junit: model/build/test-results/test/TEST-*.xml

build:openjdk:8:
  extends: .build
  image: openjdk:8

build:openjdk:10:
  extends: .build
  image: openjdk:10

unit:openjdk:8:
  extends: .unit
  image: openjdk:8

unit:openjdk:10:
  extends: .unit
  image: openjdk:10
